site_name: 2600.london
site_url: https://2600.london

theme:
  name: material
  palette:
    # Palette toggle for dark mode
    - scheme: slate
      toggle:
        icon: material/brightness-4
        name: Switch to light mode

    # Palette toggle for light mode
    - scheme: default
      toggle:
        icon: material/brightness-7
        name: Switch to dark mode
  font:
    text: Roboto
    code: Roboto Mono
  features:
    - search.suggest

plugins:
  - search
  - roamlinks # https://github.com/Jackiexiao/mkdocs-roamlinks-pluginmk
  # - blog:
  #     blog_dir: blog
  # - rss:
  #     match_path: blog/blog/.*
  #     date_from_meta:
  #       as_creation: date
  #     categories:
  #     - categories
  #     - tags
  - mkdocs-pdf  # Render PDFs in page
                # To embed a PDF file simple use the following syntax.
                #   ![Alt text](<path to pdf>){ type=application/pdf }
                # Optionally, you can specify style constraints, e.g.
                #   ![Alt text](<path to pdf>){ type=application/pdf style="min-height:25vh;width:100%" }

# Extensions
markdown_extensions:
  - footnotes
  - attr_list
  - toc:
      permalink: true
  - pymdownx.arithmatex:
      generic: true
  - pymdownx.superfences
  - pymdownx.details
  - pymdownx.magiclink
  - pymdownx.tasklist:
      custom_checkbox: true
  - def_list
  - pymdownx.critic
  - pymdownx.caret
  - pymdownx.keys
  - pymdownx.mark
  - pymdownx.tilde
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_code_format

extra_javascript:
  - https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-mml-chtml.js   # math rendering https://www.mathjax.org/
  - https://unpkg.com/mermaid/dist/mermaid.min.js                 # Diagram Rendering https://mermaid.js.org/
